from domain.ports.clicker_port import ClickerPort
from domain.ports.typer_port import TyperPort
from domain.ports.screen_reader_port import ScreenReaderPort
from domain.ports.config_setter_interface_port import ConfigSetterInterfacePort
from domain.ports.keyboard_listener_port import KeyboardListenerPort
from domain.ports.get_image_screen_region_use_case_port import GetImageScreenRegionUseCasePort
from domain.ports.run_program_use_case_port import RunProgramUseCasePort
