from domain.containers.run_program_use_case_container import RunProgramUseCaseContainer
from domain.containers.locate_image_in_screen_use_case_container import LocateImageInScreenUseCaseContainer
from domain.containers.click_on_image_use_case_container import ClickOnImageUseCaseContainer
from domain.containers.image_is_in_region_use_case_container import ImageIsInRegionUseCaseContainer
