from domain.value_objects.coordinates import Coordinates
from domain.value_objects.screen_region import ScreenRegion
from domain.value_objects.image_path import ImagePath
from domain.value_objects.seconds import Seconds
from domain.value_objects.money import Money
from domain.value_objects.martingale_multiplier import MartingaleMultiplier
from domain.value_objects.max_martingales import MaxMartingales
from domain.value_objects.locate_image_max_tries import LocateImageMaxTries
from domain.value_objects.profit import Profit
from domain.value_objects.image_name import ImageName
