from infrastructure.adapters.tkinter_config_setter_interface import TkinterConfigSetterInterfaceAdapter
from infrastructure.adapters.opencv_mss_screen_reader import OpencvMssScreenReaderAdapter
from infrastructure.adapters.keyboard_typer import KeyboardTyperAdapter
from infrastructure.adapters.mouse_clicker import MouseClickerAdapter
