from infrastructure.adapters.opencv_mss_screen_reader.value_objects.match import Match
from infrastructure.adapters.opencv_mss_screen_reader.value_objects.match_value import MatchValue
from infrastructure.adapters.opencv_mss_screen_reader.value_objects.match_size import MatchSize
from infrastructure.adapters.opencv_mss_screen_reader.value_objects.match_location import MatchLocation
