from infrastructure.adapters.tkinter_config_setter_interface.validations.validate_integer import validate_integer
from infrastructure.adapters.tkinter_config_setter_interface.validations.validate_float import validate_float
from infrastructure.adapters.tkinter_config_setter_interface.validations.validate_money import validate_money
